version: '3.8'

services:
  dash:
    build: .
    ports:
      - "6262:80"
    volumes:
      - dash-config:/config
    restart: unless-stopped
    container_name: multidash

volumes:
  dash-config:
